name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.12.0
  google_sign_in: 5.2.4
  firebase_auth: 3.3.7
  lottie: 1.2.2
  introduction_screen: 3.0.0
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.1.2
  get_storage: 2.0.3
  cloud_firestore: 3.1.10
  intl: 0.17.0
  image_picker: 0.8.5
  firebase_storage: 10.2.12
  flutter: 
    sdk: flutter
  firebase_storage_web: ^3.2.12

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_chat.png"

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

